### PR TITLE
Remove some if-statements and use named return.

### PR DESCRIPTION
**Pull request by albertoleal**
Hey, @scorphus!

I have removed some if statements and made use of "named return" for the missing functions. Besides that, I removed the address validation because an empty string is the default value when we do not inform that.

:coffee:

### CODE REVIEW

**Comment by albertoleal** [comment]
Network blip? `Bad response status from coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}`

**Comment by scorphus** [comment]
Hey, @albertoleal! First things first, thank you for your contributions! :coffee: 

I'm eager to accept them but unfortunately latest merges rendered your pull request conflicting.

Would you care to rebase your work on top of master?

**Comment by albertoleal** [comment]
Done :coffee:

**Comment by scorphus** [comment]
Thank you, brother! :coffee:

**Pull request merged**
